version: '3'

networks:
  mapper-net:

services:
  db:
    image: postgres:12.6
    restart: unless-stopped
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      mapper-net:
        aliases:
          - db
  redis:
    image: redis:6-alpine
    networks:
      mapper-net:
        aliases:
          - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      VUE_APP_API_URL: "http://localhost:#{BACKEND_PORT}"
    networks:
      mapper-net:
        aliases:
          - frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      RAILS_ENV: production
      SESSION_SECRET: "${SESSION_SECRET}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?pool=5&timeout=5000"
      REDIS_URL: "redis://redis:6379/0"
      MAILER_FROM: "noreply@feminizidmap.org"
      FRONTEND_URL: "http://localhost:${FRONTEND_PORT}"
      BACKEND_URL: "http://localhost:${BACKEND_PORT}"
    networks:
      mapper-net:
        aliases:
          - backend
