name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_rails:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      REDIS_URL: "redis://localhost:6379/0"
      SESSION_SECRET: "thisisonlyfortesting"
      DATABASE_TEST_URL: "postgresql://postgres:postgres@localhost:5432/mapper_test?pool=5&timeout=5000"
      FRONTEND_URL: "http://localhost:8080"
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    strategy:
      matrix:
        ruby-version: ['3.0.0']
    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: backend
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Build App
      run: bin/rails db:setup
    - name: Run Tests
      run: bundle exec rspec
    - name: Coveralls
      run: |
        echo "repo_token: ${{secrets.COVERALLS_REPO_TOKEN}}" > .coveralls.yml
        bundle exec coveralls push

  test_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2.1.0
        with:
          path: node_modules
          key: ubuntu-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run ESLint
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
