name: Deploy

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [ main ]
    types:
      - completed

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAMEdview}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
