name: Deploy

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [ main ]
    types:
      - completed

jobs:
  staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: deploy backend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      ## The frontend gets deployed to netlify through a webhook now
      #- uses: akhileshns/heroku-deploy@v3.12.12
      #  name: deploy frontend
      #  with:
      #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #    heroku_app_name: ${{secrets.HEROKU_FRONTEND_APP_NAME}}
      #    heroku_email: ${{secrets.HEROKU_EMAIL}}
